[package]
name = "fedora-setup"
version = "1.0.1"
edition = "2021"

[dependencies]
dialoguer = "0.12.0"
console = "0.16.2"
colored = "3.0.0"
anyhow = "1.0.100"
dirs = "6.0.0"
cmd_lib = "2.0.0"
clap = { version = "4.5.54", features = ["derive"] }

[[bin]]
name = "fedora-setup"
path = "src/main.rs"
